### ISSUE TITLE
Meta: Great to have this.

### ISSUE THREAD

**Issue by sirinath** [kaj/r4s#2]
I am unsatisfied with Hugo and Zola. I hope this evolved into a compelling alternative.

Also can you enable GitHub discussions?

**Comment by kaj** [comment]
Currently, this is very much just "my blog", with one specific styling and a bunch of markdown extensions, some of which may be generally useful, while others are specific for me (e.g. recognizing that `[Fa 17/1973]` should be a link to the seventeenth issue from 1973 of the Swedish Fantomen (the Phantom) comic in my index).

But yes, in the future it would be nice to split that into a smaller crate for "my blog" with a dependency to a "blog base" crate that could be useful for others.

Yes, enabeling GitHub discussions may be a good start for that.

For the moment though, most of the time I have availiable for r4s goes into making it complete enough to handle my blog.  Breaking out a blog-base comes later.

**Comment by sirinath** [comment]
If it can be eventually made configurable where you blog would be one configuration it would be more useful.
